title: "Демонстрация детектора"
uploads_dir: "/workspace/uploads"
downloads_dir: "/workspace/downloads"
results_dir: "/workspace/results"

Detector:
  weights_path: "./models/primary/model.pt"
  iou_thres: 0.5
  conf_thres: 0.3
  imgsz: 1024


